#!/bin/sh
set -e

for package in python-yaml python-lxml python-libvirt; do
    if [ "$(dpkg --status -- $package 2>/dev/null|sed -n 's/^Status: //p')" != "install ok installed" ]; then
        # add a space after old values
        missing="${missing:+$missing }$package"
    fi
done
if [ -n "$missing" ]; then
    echo "$0: missing required packages, please install them:" 1>&2
    echo "  sudo apt-get install $missing"
    exit 1
fi
