#!/bin/sh
set -e

# ssh ubuntu@chef-NAME-server.front.sepia.ceph.com <install-chef-server

SERVER_URL="http://$(hostname).front.sepia.ceph.com:4000/"

sudo apt-key add - <<'EOF'
# Key from http://apt.opscode.com/packages@opscode.com.gpg.key
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.9 (GNU/Linux)

mQGiBEppC7QRBADfsOkZU6KZK+YmKw4wev5mjKJEkVGlus+NxW8wItX5sGa6kdUu
twAyj7Yr92rF+ICFEP3gGU6+lGo0Nve7KxkN/1W7/m3G4zuk+ccIKmjp8KS3qn99
dxy64vcji9jIllVa+XXOGIp0G8GEaj7mbkixL/bMeGfdMlv8Gf2XPpp9vwCgn/GC
JKacfnw7MpLKUHOYSlb//JsEAJqao3ViNfav83jJKEkD8cf59Y8xKia5OpZqTK5W
ShVnNWS3U5IVQk10ZDH97Qn/YrK387H4CyhLE9mxPXs/ul18ioiaars/q2MEKU2I
XKfV21eMLO9LYd6Ny/Kqj8o5WQK2J6+NAhSwvthZcIEphcFignIuobP+B5wNFQpe
DbKfA/0WvN2OwFeWRcmmd3Hz7nHTpcnSF+4QX6yHRF/5BgxkG6IqBIACQbzPn6Hm
sMtm/SVf11izmDqSsQptCrOZILfLX/mE+YOl+CwWSHhl+YsFts1WOuh1EhQD26aO
Z84HuHV5HFRWjDLw9LriltBVQcXbpfSrRP5bdr7Wh8vhqJTPjrQnT3BzY29kZSBQ
YWNrYWdlcyA8cGFja2FnZXNAb3BzY29kZS5jb20+iGAEExECACAFAkppC7QCGwMG
CwkIBwMCBBUCCAMEFgIDAQIeAQIXgAAKCRApQKupg++Caj8sAKCOXmdG36gWji/K
+o+XtBfvdMnFYQCfTCEWxRy2BnzLoBBFCjDSK6sJqCu5Ag0ESmkLtBAIAIO2SwlR
lU5i6gTOp42RHWW7/pmW78CwUqJnYqnXROrt3h9F9xrsGkH0Fh1FRtsnncgzIhvh
DLQnRHnkXm0ws0jV0PF74ttoUT6BLAUsFi2SPP1zYNJ9H9fhhK/pjijtAcQwdgxu
wwNJ5xCEscBZCjhSRXm0d30bK1o49Cow8ZIbHtnXVP41c9QWOzX/LaGZsKQZnaMx
EzDk8dyyctR2f03vRSVyTFGgdpUcpbr9eTFVgikCa6ODEBv+0BnCH6yGTXwBid9g
w0o1e/2DviKUWCC+AlAUOubLmOIGFBuI4UR+rux9affbHcLIOTiKQXv79lW3P7W8
AAfniSQKfPWXrrcAAwUH/2XBqD4Uxhbs25HDUUiM/m6Gnlj6EsStg8n0nMggLhuN
QmPfoNByMPUqvA7sULyfr6xCYzbzRNxABHSpf85FzGQ29RF4xsA4vOOU8RDIYQ9X
Q8NqqR6pydprRFqWe47hsAN7BoYuhWqTtOLSBmnAnzTR5pURoqcquWYiiEavZixJ
3ZRAq/HMGioJEtMFrvsZjGXuzef7f0ytfR1zYeLVWnL9Bd32CueBlI7dhYwkFe+V
Ep5jWOCj02C1wHcwt+uIRDJV6TdtbIiBYAdOMPk15+VBdweBXwMuYXr76+A7VeDL
zIhi7tKFo6WiwjKZq0dzctsJJjtIfr4K4vbiD9Ojg1iISQQYEQIACQUCSmkLtAIb
DAAKCRApQKupg++CauISAJ9CxYPOKhOxalBnVTLeNUkAHGg2gACeIsbobtaD4ZHG
0GLl8EkfA8uhluM=
=zKAm
-----END PGP PUBLIC KEY BLOCK-----
EOF

sudo tee /etc/apt/sources.list.d/chef.list >/dev/null <<EOF
deb http://apt.opscode.com/ $(lsb_release -cs)-0.10 main
EOF

sudo debconf-set-selections <<EOF
chef-server-webui	chef-server-webui/admin_password	password	chefdemoweb
chef-solr	chef-solr/amqp_password	password	chefdemosolr
chef	chef/chef_server_url	string	$SERVER_URL
EOF

sudo apt-get update
sudo env DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical \
  apt-get -q install --no-install-recommends --assume-yes -- chef-server

# be careful to handle both running via cloud-init or via "ssh
# ubuntu@... <script".. such an ugly kludge
install -d -m0700 --owner=ubuntu --group=ubuntu /home/ubuntu/.chef
sudo knife configure --initial --defaults --user='admin' --key="/home/ubuntu/.chef/admin.pem" --server-url="$SERVER_URL" --repository="/home/ubuntu/chef"
if [ "$(id -u -n)" = "root" ]; then
    # the config gets written in the wrong place when running as root,
    # fix it up
    mv /root/.chef/knife.rb /home/ubuntu/.chef/knife.rb
    rmdir /root/.chef
fi
sudo chmod u=r,go= /home/ubuntu/.chef/admin.pem /home/ubuntu/.chef/knife.rb
sudo chown ubuntu:ubuntu ~ubuntu/.chef/admin.pem ~ubuntu/.chef/knife.rb
